.TH TWRAP 1 2022-10-17 "twrap 1.0.0"

.SH NAME
twrap \- simple text wrapper utility

.SH SYNOPSIS
.B twrap
[\fB-fs\fR] [\fB\-l \fIline_number\fR]

.SH OPTIONS
.TP
.BR \-l ", " \-\-line " " \fIline_number
specifies how many character each line should have. if not passsed, then the default \fIline_number\fR will set to 65
.TP
.BR \-f ", " \-\-force
if the current line contains only one single long word longer than expected \fIline_number\fR then it forces the word to break (open new line)
.TP
.BR \-s ", " \-\-skip
does not care about word proportion, if current line count has exceeded the desired \fIline_number\fR then it breaks up the word

.SH DESCRIPTION
Wraps FILE or standard input when no FILE passed onto standard output.

.SH EXAMPLES
.TP
.B twrap < \fIfoo.txt
wraps the foo.txt FILE then print it onto standard output.
.TP
.B cat \fIfoo.txt \fR| \fBtwrap
uses \fBcat\fR(1) to supply foo.txt as standard input.

.SH SEE ALSO
\fBcat\fR(1), \fBfold\fR(1)
